obj: maxentirl
IS: false
seed: 1
cuda: 0
env:
  env_name: CartPoleContinuous-v0
  T: 500
  state_indices: all
irl:
  training_trajs: 10
  n_itrs: 100
  save_interval: 0
  eval_episodes: 10
  expert_episodes: 1
  resample_episodes: 10
sac:
  k: 1
  epochs: 10
  log_step_interval: 5000
  update_every: 1
  random_explore_episodes: 5
  update_num: 1
  batch_size: 256
  lr: 3e-4
  alpha: 0.2
  automatic_alpha_tuning: false
  buffer_size: 1000000
  num_test_episodes: 10
  reinitialize: false
reward:
  use_bn: false
  residual: false
  hid_act: relu
  hidden_sizes: [64, 64]
  clamp_magnitude: 10
  lr: 1e-4
  weight_decay: 1e-3
  gradient_step: 1
  momentum: 0.9
  alpha: 0.1
  num_epochs: 700
  batch_size: 256
